logging:
  level:
    '[org.springframework.web]': trace
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:tododb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
  mvc:
    format:
      date: yyyy-MM-dd
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
springdoc:
  show-actuator: false
